---
title: "Jupyter Notebooks"
author: "Sohail Nizam<br> <span style = 'font-size: 50%;'> Emory University<br> Department of Biostatistics and Bioinformatics </span>"
date: "Foo"
tldr: "Quick use your mouse a little while David isn't looking!"
recording: ""
reading: ""
breakoutsoln: ""
start: "0:0:0"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    nature:
      titleSlideClass: ["left", "middle", "inverse"]
      highlightStyle: tomorrow-night-blue
      highlightLanguage: bash

---

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
extra_css <- list(
    "ul" = list(`margin-bottom` = "0.5em",
      `margin-top` = "0.5em"),
        "p" = list(`margin-bottom` = "0.25em"),
        "ul li" = list(`margin-bottom` = "10px"),
        "a" = list(color = "#007dba"),
        "a:hover" = list("text-decoration" = "underline"),
        ".green" = list(color = "#348338"),
        ".red" = list(color = "#da291c")
)
style_mono_accent(
  base_color = "#012169",
  header_font_google = google_font("DM Sans"),
  text_font_google   = google_font("DM Sans", "400", "400i"),
  code_font_google   = google_font("Courier Prime"),
  extra_css = extra_css
)
```
<style type="text/css">
.remark-slide-content {
    font-size: 22px
}
</style>

## An interactive way to create reports

Imagine taking a compiled Rmarkdown report and typing directly into each code or markdown chunk!
 
* Run code chunks one at a time
* Make changes to text, figures, and other output without recompiling each time
* Write bash code within the notebook to install packages
* Easily embed HTML into text chunks 
* Share your report as HTML, PDF, and more
* Share your notebook so others build off your work 


---

## JSON files

* Jupyter Notebooks are saved as .ipynb files
* .ipynb files are just JSON (Java Script Object Notation) files
* JSON files are just plain text and thus can be read/created in any programming language
* For python users: syntax looks just like a python dictionary



---

## Opening Jupyter Notebooks

* Navigate to your project directory and run this command in terminal

```{bash, openjn, eval = FALSE}
jupyter notebook
```

* A browser window will open with address `http://localhost:8888/tree`
* You should see the files that live in the directory you ran the command from


SCREENSHOT HERE


---

## Kernels

From the Jupyter Notebook docs:

"Kernels are programming language specific processes that run independently and interact with the Jupyter Applications and their user interfaces."

Find a list of all available kernels [here](https://github.com/jupyter/jupyter/wiki/Jupyter-kernels). We are most interested in:

* Ipython
* IRKernel


---

## Keyboard Shortcuts




---

## Magics




---

## Sharing notebooks




---

## Exporting notebooks





